name: 'Module Release Locator'
description: 'Locates and processes release source code from GitHub repositories'
author: 'WippyAI'

inputs:
  repository:
    description: 'The repository to locate release from (e.g., wippyai/module-hello)'
    required: true
  tag:
    description: 'The release tag to locate (e.g., v1.0.0)'
    required: true
  token:
    description: 'GitHub token for authentication'
    required: true
  module_id:
    description: 'The UUID of the module to upload to'
    required: true
  username:
    description: 'Username for modules.wippy.ai authentication'
    required: true
  password:
    description: 'Password for modules.wippy.ai authentication'
    required: true

outputs:
  release_url:
    description: 'URL of the located release'
  source_code_url:
    description: 'URL of the release source code'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - shell: bash
      run: |
        chmod +x main.sh
        ./main.sh \
          --repository "${{ inputs.repository }}" \
          --tag "${{ inputs.tag }}" \
          --token "${{ inputs.token }}" \
          --module-id "${{ inputs.module_id }}" \
          --username "${{ inputs.username }}" \
          --password "${{ inputs.password }}" 