name: Test Release Locator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      
      - name: Clone proto repository
        run: |
          if [ ! -d "proto" ]; then
            git clone "https://x-access-token:${{ secrets.PRIVATE_REPO_TOKEN }}@github.com/wippyai/module-registry-proto.git" proto
          fi
      
      - name: Download source code
        run: |
          SOURCE_CODE_URL="https://github.com/wippyai/module-hello/archive/refs/tags/v1.0.0.zip"
          curl -L -H "Authorization: token ${{ secrets.PRIVATE_REPO_TOKEN }}" -o source.zip "$SOURCE_CODE_URL"
      
      - name: Build and run upload tool
        run: |
          # Build the upload tool
          go mod tidy
          go build -o upload-tool
          
          # Debug information
          echo "Debug: Uploading archive for module ID: ${{ secrets.MODULE_ID }}"
          echo "Debug: Archive size: $(stat -c %s source.zip) bytes"
          echo "Debug: Checking upload-tool location:"
          ls -la upload-tool
          
          # Run the upload tool
          ./upload-tool "${{ secrets.MODULE_ID }}" "v1.0.0" "source.zip" "${{ secrets.WIPPY_USERNAME }}" "${{ secrets.WIPPY_PASSWORD }}"
          
          # Check exit code
          if [ $? -ne 0 ]; then
            echo "::error::Failed to upload archive" >&2
            exit 1
          fi
      
      - name: Cleanup
        run: |
          rm -f source.zip
          rm -f upload-tool