name: Test Release Locator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      
      - name: Install jq
        run: sudo apt-get install -y jq
      
      - name: Test the action
        uses: ./
        with:
          repository: 'wippyai/module-hello'
          tag: 'v1.0.0'
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          module_id: ${{ secrets.MODULE_ID }}
          username: ${{ secrets.WIPPY_USERNAME }}
          password: ${{ secrets.WIPPY_PASSWORD }}