name: Build and Test Upload Tool

on:
  push:
    paths:
      - 'main.sh'
      - '.github/workflows/upload.yml'
  pull_request:
    paths:
      - 'main.sh'
      - '.github/workflows/upload.yml'

env:
  REPOSITORY: ${{ vars.REPOSITORY }}
  TAG: ${{ vars.ref_name }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MODULE_ID: ${{ secrets.MODULE_ID }}
  USERNAME: ${{ secrets.WIPPY_USERNAME }}
  PASSWORD: ${{ secrets.WIPPY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Upload module archive
        run: |
          if ! ./main.sh \
            --repository "${{ env.REPOSITORY }}" \
            --tag "${{ env.TAG }}" \
            --token "${{ env.GITHUB_TOKEN }}" \
            --module-id "${{ env.MODULE_ID }}" \
            --username "${{ env.USERNAME }}" \
            --password "${{ env.PASSWORD }}"; then
            echo "::error::Failed to upload module archive"
            exit 1
          fi 